name: myartist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  adaptive_breakpoints: ^0.1.4
  adaptive_components: ^0.0.7
  adaptive_navigation: ^0.0.7
  animations: ^2.0.5
  audioplayers: ^1.1.1
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  desktop_window: ^0.4.0
  dynamic_color: ^1.5.4
  english_words: ^4.0.0
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_media_metadata: ^1.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.1.0
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  material_color_utilities: ^0.1.5
  shared_preferences: ^2.0.15
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.6

dev_dependencies:
  hive_generator: ^1.1.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
